import assert from "node:assert/strict";
import test from "node:test";

import {
  completionInvoiceFingerprint,
  planCompletionInvoice,
} from "../completionInvoice.js";

const marker = (receiptId) => ({
  v: 2,
  receiptId,
  completedAt: "2026-08-03T14:00:00.000Z",
});

const invoicing = {
  numberPrefix: "INV-",
  nextNumber: 2000,
  dueDays: 15,
  taxRate: "6",
  terms: "Payment is due within 15 days.",
};

const baseClient = (overrides = {}) => ({
  id: "client-1",
  name: "Jordan Hale",
  address: "10 Main Street",
  email: "jordan@example.com",
  history: [],
  ...overrides,
});

test("one-off completion creates one deterministic draft with service, billable parts, and billable products", () => {
  const stop = { sid: "repair-1", clientId: "client-1", type: "Repair Visit" };
  const entry = {
    sid: stop.sid,
    completionReceiptId: "receipt-repair-1",
    services: [{ id: "svc-repair", name: "Repair labor", price: "175", cost: "60" }],
    invoice: "$175.00",
    partsUsed: [
      { id: "part-valve", name: "Valve", qty: 2, unit: "pieces", retailPer: 25, costPer: 10, bill: true },
      { id: "part-shop", name: "Shop supply", qty: 1, retailPer: 5, costPer: 2, bill: false },
    ],
    productsPurchased: [
      { id: "product-skimmer", name: "Skimmer plate", qty: 1, price: 79.99, cost: 35, bill: true },
      { id: "product-warranty", name: "Warranty replacement", qty: 1, price: 20, cost: 20, bill: false },
    ],
  };
  const existingInvoices = [{ id: "old", number: "INV-2004" }];
  const result = planCompletionInvoice({
    invoices: existingInvoices,
    invoicing,
    schedule: [{ date: "08/03/2026", stops: [stop] }],
    completed: { [stop.sid]: marker(entry.completionReceiptId) },
    stop,
    entry,
    client: baseClient(),
    receiptId: entry.completionReceiptId,
    completedAt: "2026-08-03T14:00:00.000Z",
    now: Date.parse("2026-08-03T14:00:00.000Z"),
  });

  assert.equal(result.changed, true);
  assert.deepEqual(result.outcome, {
    status: "created",
    kind: "one-off",
    invoiceId: "iv_stop_repair-1",
    invoiceNumber: "INV-2005",
    sourceStopId: "repair-1",
  });
  assert.equal(result.invoices.length, 2);
  assert.equal(existingInvoices.length, 1, "the source array remains unchanged");
  const invoice = result.invoices[0];
  assert.equal(invoice.status, "Draft");
  assert.equal(invoice.source, "completed-stop");
  assert.equal(invoice.sourceStopId, stop.sid);
  assert.equal(invoice.sourceCompletionReceiptId, entry.completionReceiptId);
  assert.equal(invoice.date, "08/03/2026");
  assert.equal(invoice.dueDate, "08/18/2026");
  assert.equal(invoice.taxRate, "6");
  assert.equal(invoice.qbSyncStatus, "local");
  assert.equal(invoice.autoGeneratedBy, "stop-completion");
  assert.equal(invoice.autoDraftFingerprint, completionInvoiceFingerprint(invoice));
  assert.deepEqual(
    invoice.lineItems.map(({ desc, qty, unitPrice, unitCost, taxable, kind, refId }) => ({
      desc, qty, unitPrice, unitCost, taxable, kind, refId,
    })),
    [
      { desc: "Repair labor", qty: "1", unitPrice: "175", unitCost: "60", taxable: false, kind: "service", refId: "svc-repair" },
      { desc: "Valve", qty: "2", unitPrice: "25", unitCost: "10", taxable: true, kind: "part", refId: "part-valve" },
      { desc: "Skimmer plate", qty: "1", unitPrice: "79.99", unitCost: "35", taxable: true, kind: "product", refId: "product-skimmer" },
    ],
  );
});

test("one-off completion is idempotent by deterministic source stop id", () => {
  const stop = { sid: "one-off-idempotent", clientId: "client-1", type: "Service Call" };
  const input = {
    invoices: [],
    invoicing,
    schedule: [{ date: "08/04/2026", stops: [stop] }],
    completed: { [stop.sid]: marker("receipt-once") },
    stop,
    entry: { sid: stop.sid, completionReceiptId: "receipt-once", invoice: "$100.00" },
    client: baseClient(),
    completedAt: "2026-08-04T13:00:00.000Z",
    now: Date.parse("2026-08-04T13:00:00.000Z"),
  };
  const first = planCompletionInvoice(input);
  const replay = planCompletionInvoice({ ...input, invoices: first.invoices });

  assert.equal(first.invoices[0].id, "iv_stop_one-off-idempotent");
  assert.equal(replay.changed, false);
  assert.equal(replay.invoices, first.invoices);
  assert.equal(replay.invoices.length, 1);
  assert.deepEqual(replay.outcome, {
    status: "existing",
    kind: "one-off",
    invoiceId: "iv_stop_one-off-idempotent",
    invoiceNumber: "INV-2000",
    sourceStopId: "one-off-idempotent",
  });
});

test("one-off draft reconciles saved Amount Charged without discarding meaningful service lines", () => {
  const stop = { sid: "repair-adjusted", clientId: "client-1", type: "Repair Visit" };
  const result = planCompletionInvoice({
    invoices: [],
    invoicing,
    schedule: [{ date: "08/04/2026", stops: [stop] }],
    completed: { [stop.sid]: marker("receipt-adjusted") },
    stop,
    entry: {
      sid: stop.sid,
      completionReceiptId: "receipt-adjusted",
      quoted_price: 175,
      invoice: "$175.00",
      services: [
        { id: "svc-diagnostic", name: "Diagnostic", price: 125, cost: 35 },
        { id: "svc-repair", name: "Repair labor", price: 100, cost: 40 },
      ],
      partsUsed: [
        { id: "part-switch", name: "Replacement switch", qty: 1, retailPer: 25, costPer: 10, bill: true },
      ],
    },
    client: baseClient(),
    completedAt: "2026-08-04T13:00:00.000Z",
  });

  assert.equal(result.changed, true);
  const invoice = result.invoices[0];
  assert.deepEqual(
    invoice.lineItems.map(({ id, desc, qty, unitPrice, unitCost, costKnown, kind }) => ({
      id, desc, qty, unitPrice, unitCost, costKnown, kind,
    })),
    [
      { id: "il_stop_repair-adjusted_service_svc-diagnostic", desc: "Diagnostic", qty: "1", unitPrice: "125", unitCost: "35", costKnown: true, kind: "service" },
      { id: "il_stop_repair-adjusted_service_svc-repair", desc: "Repair labor", qty: "1", unitPrice: "100", unitCost: "40", costKnown: true, kind: "service" },
      { id: "il_stop_repair-adjusted_service_adjustment", desc: "Service price adjustment", qty: "1", unitPrice: "-50", unitCost: "0", costKnown: true, kind: "service" },
      { id: "il_stop_repair-adjusted_part_part-switch", desc: "Replacement switch", qty: "1", unitPrice: "25", unitCost: "10", costKnown: true, kind: "part" },
    ],
  );
  const serviceTotal = invoice.lineItems
    .filter((line) => line.kind === "service")
    .reduce((sum, line) => sum + Number(line.qty) * Number(line.unitPrice), 0);
  assert.equal(serviceTotal, 175, "service lines reconcile exactly to the saved visit charge");
  assert.equal(
    invoice.lineItems.reduce((sum, line) => sum + Number(line.qty) * Number(line.unitPrice), 0),
    200,
    "billable parts remain additional to Amount Charged",
  );
});

for (const frequency of ["Weekly", "Bi-Weekly"]) {
  test(`${frequency} maintenance waits for the final non-cancelled stop, then creates one monthly draft`, () => {
    const prefix = frequency === "Weekly" ? "weekly" : "biweekly";
    const firstStop = { sid: `${prefix}-1`, clientId: "client-1", type: `${frequency} Service` };
    const finalStop = { sid: `${prefix}-2`, clientId: "client-1", type: `${frequency} Service` };
    const cancelledStop = { sid: `${prefix}-cancelled`, clientId: "client-1", type: `${frequency} Service`, cancelled: true };
    const otherMonthStop = { sid: `${prefix}-september`, clientId: "client-1", type: `${frequency} Service` };
    const oneOffRepair = { sid: `${prefix}-repair`, clientId: "client-1", type: "Repair Visit" };
    const schedule = [
      { date: "08/03/2026", stops: [firstStop] },
      { date: "08/17/2026", stops: [finalStop] },
      { date: "08/24/2026", stops: [cancelledStop] },
      { date: "08/25/2026", stops: [oneOffRepair] },
      { date: "09/01/2026", stops: [otherMonthStop] },
    ];
    const firstEntry = {
      sid: firstStop.sid,
      completionReceiptId: `receipt-${prefix}-1`,
      partsUsed: [{ id: "part-valve", name: "Valve", qty: 1, unit: "piece", retailPer: 20, costPer: 8, bill: true }],
      productsPurchased: [{ id: "product-bacteria", name: "Bacteria", qty: 1, price: 15, cost: 5, bill: true }],
    };
    const finalEntry = {
      sid: finalStop.sid,
      completionReceiptId: `receipt-${prefix}-2`,
      partsUsed: [
        { id: "part-valve", name: "Valve", qty: 2, unit: "piece", retailPer: 20, costPer: 8, bill: true },
        { id: "part-included", name: "Included part", qty: 1, retailPer: 99, costPer: 10, bill: false },
      ],
      productsPurchased: [{ id: "product-bacteria", name: "Bacteria", qty: 2, price: 15, cost: 5, bill: true }],
    };
    const client = baseClient({
      planFreq: frequency,
      monthlyRate: "600",
      history: [firstEntry],
    });

    const beforeFinal = planCompletionInvoice({
      invoices: [],
      invoicing,
      schedule,
      completed: { [firstStop.sid]: marker(firstEntry.completionReceiptId) },
      stop: firstStop,
      entry: firstEntry,
      client,
      receiptId: firstEntry.completionReceiptId,
      completedAt: "2026-08-03T14:00:00.000Z",
    });
    assert.equal(beforeFinal.changed, false);
    assert.equal(beforeFinal.outcome.status, "pending");
    assert.deepEqual(beforeFinal.outcome.remainingStopIds, [finalStop.sid]);
    assert.equal(beforeFinal.outcome.visitCount, 2, "cancelled, repair, and other-month stops do not block the period");

    const afterFinal = planCompletionInvoice({
      invoices: [],
      invoicing,
      schedule,
      completed: {
        [firstStop.sid]: marker(firstEntry.completionReceiptId),
        [finalStop.sid]: marker(finalEntry.completionReceiptId),
        [otherMonthStop.sid]: marker(`receipt-${prefix}-september`),
      },
      stop: finalStop,
      entry: finalEntry,
      client,
      receiptId: finalEntry.completionReceiptId,
      completedAt: "2026-08-17T14:00:00.000Z",
      now: Date.parse("2026-08-17T14:00:00.000Z"),
    });

    assert.equal(afterFinal.changed, true);
    assert.equal(afterFinal.outcome.status, "created");
    assert.equal(afterFinal.outcome.kind, "monthly");
    assert.equal(afterFinal.outcome.period, "2026-08");
    assert.equal(afterFinal.outcome.visitCount, 2);
    const invoice = afterFinal.invoices[0];
    assert.equal(invoice.id, "iv_maint_client-1_2026-08");
    assert.equal(invoice.source, "monthly-maintenance");
    assert.equal(invoice.autoPeriod, "2026-08");
    assert.deepEqual(invoice.sourceStopIds, [firstStop.sid, finalStop.sid]);
    assert.deepEqual(invoice.sourceCompletionReceiptIds, [firstEntry.completionReceiptId, finalEntry.completionReceiptId]);
    assert.deepEqual(
      invoice.lineItems.map(({ desc, qty, unitPrice, kind }) => ({ desc, qty, unitPrice, kind })),
      [
        { desc: "Monthly service — August 2026", qty: "1", unitPrice: "600", kind: "service" },
        { desc: "Valve", qty: "3", unitPrice: "20", kind: "part" },
        { desc: "Bacteria", qty: "3", unitPrice: "15", kind: "product" },
      ],
    );

    const replay = planCompletionInvoice({
      invoices: afterFinal.invoices,
      invoicing,
      schedule,
      completed: {
        [firstStop.sid]: marker(firstEntry.completionReceiptId),
        [finalStop.sid]: marker(finalEntry.completionReceiptId),
      },
      stop: finalStop,
      entry: finalEntry,
      client,
    });
    assert.equal(replay.changed, false);
    assert.equal(replay.invoices.length, 1);
    assert.equal(replay.outcome.status, "existing");
    assert.equal(replay.outcome.invoiceId, invoice.id);
  });
}

test("a later same-month completion rebuilds only an untouched monthly auto-draft", () => {
  const firstStop = { sid: "monthly-later-1", clientId: "client-1", type: "Weekly Service" };
  const laterStop = { sid: "monthly-later-2", clientId: "client-1", type: "Weekly Service" };
  const firstEntry = {
    sid: firstStop.sid,
    completionReceiptId: "receipt-monthly-later-1",
    productsPurchased: [{ id: "bacteria", name: "Bacteria", qty: 1, price: 15, cost: 5, bill: true }],
  };
  const laterEntry = {
    sid: laterStop.sid,
    completionReceiptId: "receipt-monthly-later-2",
    productsPurchased: [{ id: "bacteria", name: "Bacteria", qty: 2, price: 15, cost: 5, bill: true }],
    partsUsed: [{ id: "valve", name: "Valve", qty: 1, retailPer: 20, costPer: 8, bill: true }],
  };
  const client = baseClient({ planFreq: "Weekly", monthlyRate: "400", history: [firstEntry] });
  const first = planCompletionInvoice({
    invoices: [],
    invoicing,
    schedule: [{ date: "08/03/2026", stops: [firstStop] }],
    completed: { [firstStop.sid]: marker(firstEntry.completionReceiptId) },
    stop: firstStop,
    entry: firstEntry,
    client,
    completedAt: "2026-08-03T14:00:00.000Z",
    now: Date.parse("2026-08-03T14:00:00.000Z"),
  });
  const original = first.invoices[0];

  const laterInput = {
    invoices: first.invoices,
    invoicing,
    schedule: [
      { date: "08/03/2026", stops: [firstStop] },
      { date: "08/17/2026", stops: [laterStop] },
    ],
    completed: {
      [firstStop.sid]: marker(firstEntry.completionReceiptId),
      [laterStop.sid]: marker(laterEntry.completionReceiptId),
    },
    stop: laterStop,
    entry: laterEntry,
    client,
    completedAt: "2026-08-17T14:00:00.000Z",
    now: Date.parse("2026-08-17T14:00:00.000Z"),
  };
  const updated = planCompletionInvoice(laterInput);

  assert.equal(updated.changed, true);
  assert.deepEqual(updated.outcome, {
    status: "updated",
    kind: "monthly",
    period: "2026-08",
    invoiceId: original.id,
    invoiceNumber: original.number,
    visitCount: 2,
  });
  const rebuilt = updated.invoices[0];
  assert.equal(rebuilt.id, original.id);
  assert.equal(rebuilt.number, original.number);
  assert.equal(rebuilt.date, original.date);
  assert.equal(rebuilt.createdAt, original.createdAt);
  assert.deepEqual(rebuilt.sourceStopIds, [firstStop.sid, laterStop.sid]);
  assert.deepEqual(
    rebuilt.lineItems.map(({ desc, qty, unitPrice, kind }) => ({ desc, qty, unitPrice, kind })),
    [
      { desc: "Monthly service — August 2026", qty: "1", unitPrice: "400", kind: "service" },
      { desc: "Bacteria", qty: "3", unitPrice: "15", kind: "product" },
      { desc: "Valve", qty: "1", unitPrice: "20", kind: "part" },
    ],
  );
  assert.equal(rebuilt.autoDraftFingerprint, completionInvoiceFingerprint(rebuilt));

  const replay = planCompletionInvoice({ ...laterInput, invoices: updated.invoices });
  assert.equal(replay.changed, false);
  assert.equal(replay.invoices, updated.invoices);
  assert.equal(replay.outcome.status, "existing");

  const protectedVariants = [
    { ...original, status: "Sent" },
    { ...original, qbId: "qb-monthly-later" },
    { ...original, lineItems: original.lineItems.map((line, index) => (
      index === 0 ? { ...line, unitPrice: "425" } : line
    )) },
  ];
  for (const protectedInvoice of protectedVariants) {
    const protectedResult = planCompletionInvoice({ ...laterInput, invoices: [protectedInvoice] });
    assert.equal(protectedResult.changed, false);
    assert.equal(protectedResult.invoices[0], protectedInvoice);
    assert.equal(protectedResult.outcome.status, "existing");
  }
});

test("estimate-linked completion never creates a second invoice", () => {
  const linked = { id: "iv_est_estimate-9", number: "INV-55", clientId: "client-1", status: "Draft" };
  const stop = {
    sid: "estimate-stop",
    clientId: "client-1",
    source: "estimate",
    sourceEstimateId: "estimate-9",
    linkedInvoiceId: linked.id,
  };
  const invoices = [linked];
  const result = planCompletionInvoice({
    invoices,
    invoicing,
    schedule: [{ date: "08/05/2026", stops: [stop] }],
    completed: { [stop.sid]: marker("receipt-estimate") },
    stop,
    entry: { sourceEstimateId: "estimate-9", linkedInvoiceId: linked.id, invoice: "$0" },
    client: baseClient(),
  });

  assert.equal(result.changed, false);
  assert.equal(result.invoices, invoices);
  assert.deepEqual(result.outcome, {
    status: "linked",
    kind: "estimate",
    invoiceId: linked.id,
    action: "preserve-linked-invoice",
  });
});

test("a cancelled scheduled stop fails closed even when the stale caller marks it complete", () => {
  const staleStop = { sid: "cancelled-target", clientId: "client-1", type: "Repair Visit" };
  const result = planCompletionInvoice({
    invoices: [],
    invoicing,
    schedule: [{
      date: "08/05/2026",
      stops: [{ ...staleStop, cancelled: true }],
    }],
    completed: { [staleStop.sid]: marker("receipt-cancelled") },
    stop: staleStop,
    entry: { completionReceiptId: "receipt-cancelled", invoice: "$125" },
    client: baseClient(),
  });

  assert.equal(result.changed, false);
  assert.equal(result.invoices.length, 0);
  assert.deepEqual(result.outcome, {
    status: "review_required",
    kind: "none",
    reason: "stop-cancelled",
  });
});

test("reopening removes only an untouched auto draft and returns explicit safe outcome metadata", () => {
  const stop = { sid: "reopen-stop", clientId: "client-1", type: "Repair Visit" };
  const completed = planCompletionInvoice({
    invoices: [],
    invoicing,
    schedule: [{ date: "08/06/2026", stops: [stop] }],
    completed: { [stop.sid]: marker("receipt-reopen") },
    stop,
    entry: { invoice: "$125", completionReceiptId: "receipt-reopen" },
    client: baseClient(),
    completedAt: "2026-08-06T12:00:00.000Z",
  });
  const draft = completed.invoices[0];
  const reopened = planCompletionInvoice({
    mode: "reverse",
    invoices: completed.invoices,
    stop,
    client: baseClient(),
  });

  assert.equal(reopened.changed, true);
  assert.deepEqual(reopened.invoices, []);
  assert.deepEqual(reopened.outcome, {
    status: "removed",
    kind: "one-off",
    action: "remove-untouched-draft",
    invoiceId: draft.id,
    invoiceNumber: draft.number,
    safeToRemove: true,
  });
});

test("reopening preserves a sent, QuickBooks-linked, or edited draft for office review", () => {
  const stop = { sid: "unsafe-reopen", clientId: "client-1", type: "Repair Visit" };
  const created = planCompletionInvoice({
    invoices: [],
    invoicing,
    schedule: [{ date: "08/07/2026", stops: [stop] }],
    completed: { [stop.sid]: marker("receipt-unsafe") },
    stop,
    entry: { invoice: "$75", completionReceiptId: "receipt-unsafe" },
    client: baseClient(),
  }).invoices[0];
  const unsafeVariants = [
    { ...created, status: "Sent" },
    { ...created, qbId: "qb-991" },
    { ...created, lineItems: created.lineItems.map((line) => ({ ...line, unitPrice: "80" })) },
  ];

  unsafeVariants.forEach((invoice) => {
    const result = planCompletionInvoice({
      mode: "reverse",
      invoices: [invoice],
      stop,
      client: baseClient(),
    });
    assert.equal(result.changed, false);
    assert.equal(result.invoices[0], invoice);
    assert.equal(result.outcome.status, "review_required");
    assert.equal(result.outcome.action, "preserve-invoice");
    assert.equal(result.outcome.safeToRemove, false);
  });
});

test("final monthly completion fails closed when another completed visit has no durable history", () => {
  const first = { sid: "missing-history-1", clientId: "client-1", type: "Weekly Service" };
  const final = { sid: "missing-history-2", clientId: "client-1", type: "Weekly Service" };
  const result = planCompletionInvoice({
    invoices: [],
    invoicing,
    schedule: [
      { date: "08/01/2026", stops: [first] },
      { date: "08/08/2026", stops: [final] },
    ],
    completed: {
      [first.sid]: marker("receipt-missing"),
      [final.sid]: marker("receipt-final"),
    },
    stop: final,
    entry: { sid: final.sid, completionReceiptId: "receipt-final", invoice: "$100" },
    client: baseClient({ planFreq: "Weekly", monthlyRate: "400", history: [] }),
  });

  assert.equal(result.changed, false);
  assert.deepEqual(result.outcome, {
    status: "review_required",
    kind: "monthly",
    period: "2026-08",
    reason: "completed-visit-history-missing",
    stopId: first.sid,
  });
});

test("covered recurring maintenance creates no service draft", () => {
  const stop = { sid: "prepaid-weekly", clientId: "client-1", type: "Weekly Service" };
  const entry = {
    sid: stop.sid,
    completionReceiptId: "receipt-prepaid-weekly",
    invoice: "$0",
    quoted_price: 175,
    services: [{ id: "maintenance", name: "Weekly maintenance", price: 175, cost: 50 }],
  };
  const result = planCompletionInvoice({
    invoices: [],
    invoicing,
    schedule: [{ date: "08/31/2026", stops: [stop] }],
    completed: { [stop.sid]: marker(entry.completionReceiptId) },
    stop,
    entry,
    client: baseClient({
      maintenanceBilling: {
        version: 1,
        mode: "prepaid",
        coveredFrom: "2026-08-01",
        coveredThrough: "2026-08-31",
      },
    }),
    receiptId: entry.completionReceiptId,
    completedAt: "2026-08-31T14:00:00.000Z",
  });

  assert.equal(result.changed, false);
  assert.equal(result.invoices.length, 0);
  assert.deepEqual(result.outcome, {
    status: "covered",
    kind: "prepaid-maintenance",
    action: "no-draft",
    sourceStopId: stop.sid,
    coverage: {
      version: 1,
      mode: "prepaid",
      coveredFrom: "2026-08-01",
      coveredThrough: "2026-08-31",
    },
  });
});

test("partial-period prepaid coverage stops invoice planning for review", () => {
  const stop = { sid: "prepaid-partial", clientId: "client-1", type: "Weekly Service" };
  const result = planCompletionInvoice({
    invoices: [],
    invoicing,
    schedule: [{ date: "08/15/2026", stops: [stop] }],
    completed: { [stop.sid]: marker("receipt-prepaid-partial") },
    stop,
    entry: { invoice: "$175", completionReceiptId: "receipt-prepaid-partial" },
    client: baseClient({
      planFreq: "Weekly",
      monthlyRate: "600",
      maintenanceBilling: {
        version: 1,
        mode: "prepaid",
        coveredFrom: "2026-08-15",
        coveredThrough: "2026-09-14",
      },
    }),
    completedAt: "2026-08-15T14:00:00.000Z",
  });

  assert.equal(result.changed, false);
  assert.deepEqual(result.outcome, {
    status: "review_required",
    kind: "prepaid-maintenance",
    reason: "coverage-must-span-whole-months",
    action: "fix-client-billing-policy",
  });
});

test("blank-type legacy weekly rows share the prepaid and monthly-maintenance classifier", () => {
  const first = { sid: "legacy-blank-1", clientId: "client-1", type: "" };
  const final = { sid: "legacy-blank-2", clientId: "client-1", type: "" };
  const firstEntry = { sid: first.sid, completionReceiptId: "receipt-legacy-blank-1", invoice: "$175" };
  const finalEntry = { sid: final.sid, completionReceiptId: "receipt-legacy-blank-2", invoice: "$175" };
  const common = {
    invoices: [],
    invoicing,
    schedule: [
      { date: "08/03/2026", stops: [first] },
      { date: "08/17/2026", stops: [final] },
    ],
    completed: {
      [first.sid]: marker(firstEntry.completionReceiptId),
      [final.sid]: marker(finalEntry.completionReceiptId),
    },
    stop: final,
    entry: finalEntry,
    receiptId: finalEntry.completionReceiptId,
    completedAt: "2026-08-17T14:00:00.000Z",
  };

  const prepaid = planCompletionInvoice({
    ...common,
    client: baseClient({
      planFreq: "Weekly",
      history: [firstEntry],
      maintenanceBilling: {
        version: 1,
        mode: "prepaid",
        coveredFrom: "2026-08-01",
        coveredThrough: "2026-08-31",
      },
    }),
  });
  assert.equal(prepaid.changed, false);
  assert.equal(prepaid.outcome.kind, "prepaid-maintenance");

  const monthly = planCompletionInvoice({
    ...common,
    client: baseClient({ planFreq: "Weekly", monthlyRate: "600", history: [firstEntry] }),
  });
  assert.equal(monthly.changed, true);
  assert.equal(monthly.outcome.kind, "monthly");
  assert.deepEqual(monthly.invoices[0].sourceStopIds, [first.sid, final.sid]);
});

test("covered maintenance creates an extras-only draft and reopening removes it safely", () => {
  const stop = { sid: "prepaid-extras", clientId: "client-1", type: "Bi-Weekly Maintenance" };
  const entry = {
    sid: stop.sid,
    completionReceiptId: "receipt-prepaid-extras",
    invoice: "$0",
    quoted_price: 175,
    services: [{ id: "maintenance", name: "Maintenance", price: 175, cost: 50 }],
    partsUsed: [
      { id: "valve", name: "Replacement valve", qty: 1, retailPer: 30, costPer: 12, bill: true },
      { id: "included", name: "Included washer", qty: 1, retailPer: 5, costPer: 1, bill: false },
    ],
    productsPurchased: [
      { id: "bacteria", name: "Bacteria", qty: 2, price: 15, cost: 5, bill: true },
    ],
  };
  const input = {
    invoices: [],
    invoicing,
    schedule: [{ date: "08/15/2026", stops: [stop] }],
    completed: { [stop.sid]: marker(entry.completionReceiptId) },
    stop,
    entry,
    client: baseClient({
      maintenanceBilling: {
        version: 1,
        mode: "prepaid",
        coveredFrom: "2026-08-01",
        coveredThrough: "2026-08-31",
        sourceInvoiceNumber: "PREPAID-2026",
      },
    }),
    receiptId: entry.completionReceiptId,
    completedAt: "2026-08-15T14:00:00.000Z",
  };
  const result = planCompletionInvoice(input);

  assert.equal(result.changed, true);
  assert.deepEqual(result.outcome, {
    status: "created",
    kind: "prepaid-maintenance-extras",
    invoiceId: "iv_stop_prepaid-extras",
    invoiceNumber: "INV-2000",
    sourceStopId: stop.sid,
    extraLineCount: 2,
  });
  const invoice = result.invoices[0];
  assert.equal(invoice.source, "prepaid-maintenance-extras");
  assert.equal(invoice.sourceStopId, stop.sid);
  assert.equal(invoice.sourceCompletionReceiptId, entry.completionReceiptId);
  assert.deepEqual(invoice.maintenanceBilling, {
    version: 1,
    mode: "prepaid",
    coveredFrom: "2026-08-01",
    coveredThrough: "2026-08-31",
    sourceInvoiceNumber: "PREPAID-2026",
  });
  assert.deepEqual(
    invoice.lineItems.map(({ desc, qty, unitPrice, kind }) => ({ desc, qty, unitPrice, kind })),
    [
      { desc: "Replacement valve", qty: "1", unitPrice: "30", kind: "part" },
      { desc: "Bacteria", qty: "2", unitPrice: "15", kind: "product" },
    ],
    "covered service and non-billable materials are excluded",
  );

  const replay = planCompletionInvoice({ ...input, invoices: result.invoices });
  assert.equal(replay.changed, false);
  assert.equal(replay.outcome.status, "existing");
  assert.equal(replay.outcome.kind, "prepaid-maintenance-extras");

  const reopened = planCompletionInvoice({
    mode: "reverse",
    invoices: result.invoices,
    stop,
    client: input.client,
  });
  assert.equal(reopened.changed, true);
  assert.equal(reopened.invoices.length, 0);
  assert.equal(reopened.outcome.kind, "prepaid-maintenance-extras");
  assert.equal(reopened.outcome.safeToRemove, true);
});

test("prepaid policy fails open for malformed coverage and never covers repair work", () => {
  const cases = [
    {
      stop: { sid: "prepaid-malformed", clientId: "client-1", type: "Monthly Service" },
      maintenanceBilling: {
        version: 1,
        mode: "prepaid",
        coveredFrom: "2026-02-31",
        coveredThrough: "2026-08-31",
      },
    },
    {
      stop: { sid: "prepaid-repair", clientId: "client-1", type: "Repair Visit" },
      maintenanceBilling: {
        version: 1,
        mode: "prepaid",
        coveredFrom: "2026-08-01",
        coveredThrough: "2026-08-31",
      },
    },
  ];

  for (const { stop, maintenanceBilling } of cases) {
    const result = planCompletionInvoice({
      invoices: [],
      invoicing,
      schedule: [{ date: "08/15/2026", stops: [stop] }],
      completed: { [stop.sid]: marker(`receipt-${stop.sid}`) },
      stop,
      entry: { invoice: "$125", completionReceiptId: `receipt-${stop.sid}` },
      client: baseClient({ maintenanceBilling }),
      completedAt: "2026-08-15T14:00:00.000Z",
    });
    assert.equal(result.changed, true, stop.sid);
    assert.equal(result.outcome.kind, "one-off", stop.sid);
    assert.equal(result.invoices[0].lineItems[0].unitPrice, "125", stop.sid);
  }
});
