import { readAppStatesVersioned } from "../_app-state.js";
import { invoiceMaintenanceCoverageIssue, isMaintenanceServiceExtra, withMatchedMaintenanceServiceMonths } from "../../maintenanceInvoiceCoverage.js";
import { emptyMaintenancePaymentLedger, normalizeMaintenancePaymentLedger } from "../../maintenancePaymentLedger.js";
import { buildQuickBooksInvoicePayload } from "../../quickbooksDraftSync.js";
import { findInvoiceDeletionReferences } from "../../invoiceDeletionGuard.js";
import { formatInvoiceServiceLineDescription, invoiceServiceDescriptionIssue, invoiceServiceLineMonths } from "../../invoiceServiceDescription.js";

const text = value => String(value == null ? "" : value).trim();
const list = value => Array.isArray(value) ? value : [];
const keys = ["sps_clients", "sps_invoices", "sps_maintenance_billing", "sps_schedule"];
const sourceFields = ["source", "autoPeriod", "serviceMonth", "serviceDate", "sourceVisitDates", "maintenanceService", "sourceStopId", "sourceStopIds", "sourceCompletionReceiptId", "sourceCompletionReceiptIds"];
const extraKinds = new Set(["part", "product", "treatment", "bundle", "latefee"]);
const review = (message, code = "maintenance-coverage-review", status = 409) => ({ status, code, message, reviewRequired: true });
const hasEvidence = value => value != null && value !== false && value !== ""
  && (Array.isArray(value) ? value.length > 0 : typeof value === "object" ? Object.keys(value).length > 0 : true);

function samePayerContact(left, right) {
  const normalized = value => text(value).replace(/\s+/g, " ").toLowerCase();
  const contacts = value => [normalized(value?.address), normalized(value?.email), text(value?.phone).replace(/\D/g, "")];
  const a = contacts(left);
  const b = contacts(right);
  return a.every((value, index) => !!value && value === b[index]);
}

function hasWorkProvenance(invoice) {
  // A manually selected serviceMonth describes the charge; it is not a link
  // to completed work and must not lock a never-synced draft to its old client.
  const linkedFields = [
    "autoGenerated", "autoDraftKey", "autoPeriod", "sourceEstimateId", "estimateId",
    "sourceStopId", "sourceStopIds", "stopId", "sourceVisitId", "sourceVisitIds", "sourceVisitClientId", "sourceVisitClientIds",
    "sourceCompletionReceiptId", "sourceCompletionReceiptIds", "completionReceiptId", "visitId",
    "linkedInvoiceId", "linkedScheduledStopId", "sourceReportId", "linkedReportId", "billingDisposition",
  ];
  return linkedFields.some(key => hasEvidence(invoice?.[key]))
    || list(invoice?.lineItems).some(line => linkedFields.some(key => hasEvidence(line?.[key])) || hasEvidence(line.qbLineId));
}

function canReassignManualDraft(invoice, ledger, schedule) {
  if (!ledger || text(invoice?.status).toLowerCase() !== "draft" || hasWorkProvenance(invoice)) return false;
  const origin = text(invoice.source || invoice.origin).toLowerCase();
  if (origin && !["manual", "local", "sps", "sps-way"].includes(origin)) return false;
  if (Object.entries(invoice).some(([key, value]) => /^qb(?:[A-Z_]|$)/.test(key)
    && key !== "qbCustomerId" && !(key === "qbSyncStatus" && ["local", "not-synced"].includes(text(value).toLowerCase()))
    && hasEvidence(value))) return false;
  if ([
    "sentDate", "sentAt", "emailedAt", "emailSentAt", "deliveredAt", "deliveryDate", "viewedAt", "clientViewedAt",
    "openedAt", "downloadedAt", "exportedAt", "printedAt", "sharedAt", "paymentLink", "paidDate", "paidAt",
    "payment", "payments", "paymentId", "paymentStatus", "partial", "balance", "amountPaid", "paidAmount", "creditApplied", "creditsApplied", "paymentAmount",
  ].some(key => hasEvidence(invoice[key]))) return false;
  if (findInvoiceDeletionReferences(invoice, [], schedule).blocked) return false;
  const references = source => (text(source.invoiceId || source.sourceInvoiceId) && text(source.invoiceId || source.sourceInvoiceId) === text(invoice.id))
    || (text(source.invoiceNumber || source.sourceInvoiceNumber) && text(source.invoiceNumber || source.sourceInvoiceNumber) === text(invoice.number));
  return !Object.values(ledger.policies).some(references)
    && !Object.values(ledger.allocations).some(months => Object.values(months).some(cell => cell.sources.some(references)));
}

function guardCandidate(invoice, canonical) {
  const candidate = { ...canonical, ...invoice, id: canonical?.id || "", lineItems: list(invoice.lineItems || invoice.items).map(line => {
    const originals = list(canonical?.lineItems).filter(saved => (text(line.id) && text(saved.id) === text(line.id))
      || (text(line.qbLineId) && text(saved.qbLineId) === text(line.qbLineId)));
    const saved = originals.length === 1 ? originals[0] : null;
    // Inspect the exact description the endpoint will transmit, before saved
    // evidence replaces request metadata. Otherwise an undated request could
    // check the saved October visit but send a selected November to QuickBooks.
    const result = { ...saved, ...line, desc: formatInvoiceServiceLineDescription(invoice, line) || "Service" };
    for (const key of sourceFields) if (saved?.[key] != null && (key !== "maintenanceService" || saved[key] === true)
      && (key !== "serviceMonth" || result[key] == null || hasWorkProvenance(canonical))) result[key] = saved[key];
    // Older generated monthly lines retained their period only on the invoice.
    // Preserve that verified month as line evidence so outbound dated text
    // cannot override it as though it were an editable manual default.
    if (saved && text(canonical?.autoPeriod)) {
      const months = invoiceServiceLineMonths(canonical, saved);
      if (months.length) result.sourceVisitDates = months;
    }
    return result;
  }) };
  // Existing service provenance is authoritative, even if an older browser
  // omits it or a draft editor changes the invoice's issue date. A manual month
  // without linked work can still be deliberately corrected.
  for (const key of sourceFields) if (canonical?.[key] != null && (key !== "maintenanceService" || canonical[key] === true)
    && (key !== "serviceMonth" || candidate[key] == null || hasWorkProvenance(canonical))) candidate[key] = canonical[key];
  return candidate;
}

function billingContent(invoice) {
  return JSON.stringify({
    number: text(invoice.number), date: text(invoice.date), dueDate: text(invoice.dueDate),
    taxRate: Number(invoice.taxRate || 0),
    discountType: text(invoice.invoiceDiscountType), discount: Number(invoice.invoiceDiscount || 0),
    lines: list(invoice.lineItems || invoice.items).map(line => ({
      description: formatInvoiceServiceLineDescription(invoice, line),
      qty: Number(line.qty ?? 1), unitPrice: Number(line.unitPrice ?? line.rate ?? 0),
      kind: text(line.kind || "custom"), taxable: !!line.taxable,
      serviceMonths: invoiceServiceLineMonths(invoice, line),
    })),
  });
}

function possibleMaintenance(invoice) {
  return !!invoiceMaintenanceCoverageIssue({ invoice, client: { id: "inspection", history: [] }, ledger: null });
}

export async function quickBooksMaintenanceGuard(invoice, { mode = "create", existingQuickBooksInvoice = null, onPreparedInvoice, trustedCanonicalInvoice = null } = {}) {
  const incomingLines = list(invoice?.lineItems || invoice?.items);
  // Parts and other extras are not maintenance service charges. This also keeps
  // an unrelated purchase from depending on maintenance-ledger availability.
  if (!incomingLines.some(line => !extraKinds.has(text(line.kind).toLowerCase())
    && !isMaintenanceServiceExtra({ description: line.desc || line.description || line.name || line.type })
    && Number(line.qty ?? 1) * Number(line.unitPrice ?? line.rate ?? 0) > 0)) return null;
  let snapshot;
  try {
    snapshot = await readAppStatesVersioned(keys);
  } catch (_) {
    return review("Payment coverage could not be checked. Try again before sending this invoice to QuickBooks.", "maintenance-coverage-unavailable", 503);
  }
  if (!Array.isArray(snapshot.sps_clients?.value) || !Array.isArray(snapshot.sps_invoices?.value)) {
    return review("Shared clients and invoices could not be verified. Refresh SPS before sending this invoice to QuickBooks.", "maintenance-coverage-unavailable", 503);
  }
  const clients = snapshot.sps_clients.value;
  const invoices = trustedCanonicalInvoice
    ? [...snapshot.sps_invoices.value.filter(saved => text(saved.id) !== text(trustedCanonicalInvoice.id)), trustedCanonicalInvoice]
    : snapshot.sps_invoices.value;
  const spsId = text(invoice.spsInvoiceId || invoice.id);
  const qbId = text(existingQuickBooksInvoice?.Id || invoice.qbId);
  const byId = spsId ? invoices.filter(saved => text(saved.id) === spsId) : [];
  const byQb = qbId ? invoices.filter(saved => text(saved.qbId || saved.Id) === qbId) : [];
  const canonical = byId.length === 1 ? byId[0] : byQb.length === 1 ? byQb[0] : null;
  let candidate = guardCandidate(invoice, canonical);
  const ledger = snapshot.sps_maintenance_billing?.exists
    ? normalizeMaintenancePaymentLedger(snapshot.sps_maintenance_billing.value)
    : emptyMaintenancePaymentLedger();
  const schedule = list(snapshot.sps_schedule?.value);
  // A never-linked manual draft is still editable before its first QB create.
  // The editor saves its new client only after that create succeeds, so use the
  // deliberately selected client without weakening ownership of billed work.
  const reassigningManualDraft = mode === "create" && byId.length === 1 && !qbId
    && text(invoice.clientId) && text(invoice.clientId) !== text(canonical.clientId ?? canonical.customerId)
    && (!text(invoice.source || invoice.origin) || ["manual", "local", "sps", "sps-way"].includes(text(invoice.source || invoice.origin).toLowerCase()))
    && !hasWorkProvenance(invoice) && !hasEvidence(invoice.qbCreateRequestKey)
    && canReassignManualDraft(canonical, ledger, schedule);
  const requestedClientIds = [reassigningManualDraft ? null : canonical?.clientId ?? canonical?.customerId, invoice.clientId].map(text).filter(Boolean);
  const requestedQbIds = [reassigningManualDraft ? null : canonical?.qbCustomerId, invoice.qbCustomerId, existingQuickBooksInvoice?.CustomerRef?.value].map(text).filter(Boolean);
  let client = null;
  let ownershipInvalid = byId.length > 1 || byQb.length > 1 || (byId.length === 1 && byQb.length === 1 && byId[0] !== byQb[0]);
  if (spsId && !byId.length && byQb.length) ownershipInvalid = true;
  if (canonical?.qbId && qbId && text(canonical.qbId) !== qbId) ownershipInvalid = true;
  for (const id of requestedClientIds) {
    const matches = clients.filter(entry => text(entry.id) === id);
    if (matches.length !== 1 || (client && text(client.id) !== text(matches[0].id))) ownershipInvalid = true;
    else client = matches[0];
  }
  for (const id of requestedQbIds) {
    const matches = clients.filter(entry => text(entry.qbId || entry.qbCustomerId) === id);
    // A person and their company can share a QB payer. Keep the saved SPS
    // invoice's unique owner when every alias has the same verified contact
    // details; the QB id alone must never choose a client or bypass a mismatch.
    const canonicalPayerAlias = matches.length > 1 && !ownershipInvalid && !reassigningManualDraft
      && client && text(canonical?.clientId ?? canonical?.customerId) === text(client.id)
      && text(client.qbId || client.qbCustomerId) === id
      && matches.every(entry => samePayerContact(client, entry));
    if (canonicalPayerAlias) continue;
    if (matches.length !== 1 || (client && text(client.id) !== text(matches[0].id))) ownershipInvalid = true;
    else client = matches[0];
  }
  if (client && ledger) {
    invoice = withMatchedMaintenanceServiceMonths({ invoice: { ...invoice, id: canonical?.id || "" }, client, clients, ledger, invoices });
    candidate = guardCandidate(invoice, canonical);
  }
  // Resolving a saved client's history detects generic descriptions attached to
  // covered visits as well as explicit monthly-maintenance invoice text.
  const inspectClient = client || { id: requestedClientIds[0] || "unresolved", history: [] };
  const needsCoverage = possibleMaintenance(candidate)
    || !!invoiceMaintenanceCoverageIssue({ invoice: candidate, client: inspectClient, clients, ledger: null, invoices, schedule: list(snapshot.sps_schedule?.value) });
  if (!needsCoverage) return null;
  if (!client || ownershipInvalid) {
    return review("This maintenance invoice could not be linked to one verified client. Select the correct client and sync again.", "maintenance-client-unverified");
  }
  if (mode === "create" && canonical?.qbId) {
    return review("This maintenance invoice already has a QuickBooks link. Refresh it before syncing again.", "maintenance-invoice-already-linked");
  }
  if (!ledger || (snapshot.sps_schedule?.exists && !Array.isArray(snapshot.sps_schedule.value))) {
    return review("Maintenance payment coverage could not be verified. Refresh SPS and review the covered months before billing.", "maintenance-coverage-unavailable", 503);
  }
  const descriptionIssue = invoiceServiceDescriptionIssue(invoice);
  if (descriptionIssue) return { ...descriptionIssue, status: 422, reviewRequired: true };
  // An older payload may omit the marker that tells the endpoint a generic
  // "Services" line is maintenance. Canonical history can still identify it,
  // but the outgoing description itself must contain the performed month.
  for (const [index, line] of candidate.lineItems.entries()) {
    const maintenance = invoiceMaintenanceCoverageIssue({ invoice: { ...candidate, lineItems: [line] }, client, clients, ledger: null, invoices, schedule });
    if (!maintenance) continue;
    const issue = invoiceServiceDescriptionIssue({ source: "monthly-maintenance", lineItems: [{ desc: line.desc, kind: line.kind }] });
    if (issue) return { ...issue, lineIndexes: [index], status: 409, reviewRequired: true };
  }
  // Only an unchanged canonical source invoice gets the source exemption. A
  // new request cannot borrow its ID/number to add a second covered charge.
  const preparedCanonical = canonical && withMatchedMaintenanceServiceMonths({ invoice: canonical, client, clients, ledger, invoices });
  const unchangedSource = canonical && !reassigningManualDraft && billingContent(buildQuickBooksInvoicePayload(preparedCanonical, client, {})) === billingContent(invoice);
  if (!unchangedSource) candidate.id = "";
  candidate.clientId = client.id;
  const issue = invoiceMaintenanceCoverageIssue({ invoice: candidate, client, clients, ledger, invoices, schedule: list(snapshot.sps_schedule?.value) });
  if (issue) return { ...issue, status: 409 };
  onPreparedInvoice?.(invoice);
  return null;
}
